# Generated by Django 4.2.4 on 2023-09-29 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
