# Generated by Django 4.2.4 on 2023-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0005_alter_profile_options_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(choices=[('Unspecified', 'None'), ('He/Him', 'He/Him'), ('She/Her', 'She/Her'), ('They/Them', 'They/Them')], default='Unspecified', max_length=15),
        ),
    ]
