# Generated by Django 4.2.4 on 2023-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0006_alter_profile_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
