# Generated by Django 4.2.4 on 2023-10-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0009_comment_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='status',
        ),
    ]
