# Generated by Django 4.2.4 on 2023-11-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0010_remove_articles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(choices=[('Unspecified', 'None'), ('He/Him', 'He/Him'), ('She/Her', 'She/Her'), ('They/Them', 'They/Them')], default='', max_length=15),
        ),
    ]
